[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
arb_touyi = "ESrfEP9ksSoBMNLXBnPaapVWVAoDbGKM7Kkt9RE1z8HA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/touyi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
